# Generated by Django 4.2.16 on 2026-05-16 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_description', models.TextField()),
                ('resume', models.TextField()),
                ('ai_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('ai_reasons', models.JSONField(blank=True, default=list)),
                ('ai_raw_response', models.TextField(blank=True, default='')),
                ('ai_provider', models.CharField(default='openai', max_length=32)),
                ('ai_model', models.CharField(default='', max_length=64)),
                ('candidate_name', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_by', '-created_at'], name='screening_a_created_e73b2b_idx')],
            },
        ),
    ]
